### PR TITLE
ENG-3 fix font assets

### PR DESCRIPTION
**Pull request by benjaminkreen**
This one is a doozy: there seems to be a weird confluence of issue here. I think during the rails upgrade the asset pipeline started adding digests to all precompiled assets. I tried adding the font formats to the pipeline but they got digested and I don't think the sass font-awesome library likes the added digests. At the same time, there's some half cooked ember implementation which seems like way too much work to tear out right no. The ember-cli gem is supposed to add the bower assets into the pipeline, but that seems to be both disabled and failing at the moment. So the least egregious fix at the moment seems like just shunting the bower install into `public/assets` and everybody is happy! But its a kludge. I can try pulling out ember from this, but it seems like a headache trying to compensate for all the old libraries. Thoughts?

### CODE REVIEW

**Comment by benjaminkreen** [comment]
@sgatchell @JackLaBarba since you two have closest eyes on it: I'm assuming https://github.com/thoughtbot/ember-cli-rails#deploy explains how the bower assets used to get in, since font-awesome has worked before. Let me know if you want me to clarify anything else.

**Comment by JackLaBarba** [comment]
unrelated to your changes here, I'm seeing an error when building the docker image:
```
Step 12/21 : RUN bundle install
 ---> Running in 72f6d5699230
Your Ruby version is 2.6.6, but your Gemfile specified 2.6.5
ERROR: Service 'worker' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 18
```
Presumably because a new tiny version of the ruby 2.6 docker image was released recently.

If the gemfile is going to pin us to a specific ruby tiny version, we should similarly pin it in the Dockerfile: https://github.com/PLOS/lagotto/blob/a104a3417dd2e6c6b74aaf1d64b494cbf5db185f/Dockerfile#L1

Would you mind taking care of that since you already have this PR open?

**Comment by sgatchell** [comment]
This is the sort of fix I expected.  It's cheaper than ripping out the ember frontend, if less satisfying.

**Comment by sgatchell** [comment]
confirmed Jack's finding with the ruby version. Had to blow away my ruby image first:
```
docker image rm ruby:2.6-alpine 
docker-compose build
...
Step 12/21 : RUN bundle install
 ---> Running in 7cbc47c909ec
Your Ruby version is 2.6.6, but your Gemfile specified 2.6.5
ERROR: Service 'worker' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 18
```

**Comment by sgatchell** [comment]
Looks sufficient to just add a `.5`
`FROM ruby:2.6.5-alpine`

**Pull request merged**
